from django.shortcuts import render
from django.http import HttpResponse

import random
from datetime import date

# Create your views here.

# LADDER_PAIRS = [
#     ('goods', 'words'), # ['goods', 'goody', 'woody', 'woods', 'words']
#     ('woody', 'roomy'), # ['woody', 'woozy', 'doozy', 'doomy', 'roomy']
#     ('works', 'copes'), # ['works', 'corks', 'conks', 'cones', 'copes']
#     ('cones', 'joker'), # ['cones', 'comes', 'cokes', 'jokes', 'joker']
#     ('joker', 'cages'), # ['joker', 'jokes', 'cokes', 'cakes', 'cages']
#     ('cakes', 'rates'), # ['cakes', 'makes', 'mates', 'fates', 'rates']
#     ('makes', 'dares'), # ['makes', 'males', 'tales', 'dales', 'dares']
# ]

# What this really should be...
# {
#    'm/d/yyyy' : {'start': word, 'end': word, 'sequence': [words]}
# }

LADDER_PAIRS = [
    ('world', 'mould'),
    ('sears', 'tears'),
    ('pearl', 'wears'),
    ('light', 'night'),
    ('right', 'might'),
    ('fight', 'bight'),
    ('mound', 'pound'),
    ('might', 'tight'),
    ('grime', 'prick'),
    ('trims', 'chime'),
    ('prism', 'prime'),
    ('woken', 'roman'),
    ('which', 'wrist'),
    ('droop', 'thump'),
    ('grand', 'bruin'),
    ('crumb', 'thump'),
    ('moult', 'bound'),
    ('sound', 'pound'),
    ('singe', 'winch'),
    ('mouth', 'couch'),
    ('major', 'liner'),
    ('youth', 'cough'),
    ('cinch', 'reach'),
    ('froth', 'south'),
    ('spurs', 'snort'),
    ('match', 'batch'),
    ('blast', 'meant'),
    ('oases', 'gamer'),
    ('gates', 'vapes'),
    ('bales', 'dames'),
    ('round', 'pound'),
    ('black', 'slick'),
    ('north', 'worms'),
    ('draws', 'terms'),
    ('folds', 'woods'),
    ('worry', 'woods'),
    ('weave', 'heady'),
    ('woody', 'coops'),
    ('loner', 'rower'),
    ('heart', 'hoard'),
    ('roger', 'loped'),
    ('tours', 'yourn'),
    ('crowd', 'brown'),
    ('fours', 'hours'),
    ('event', 'amens'),
    ('fever', 'levee'),
    ('tacts', 'gates'),
    ('belch', 'leach'),
    ('soils', 'hours'),
    ('stage', 'share'),
    ('lites', 'fines'),
    ('crink', 'chins'),
    ('flown', 'crowd'),
    ('zones', 'poses'),
    ('begun', 'beret'),
    ('crush', 'brush'),
    ('harry', 'berry'),
    ('whams', 'chaps'),
    ('yeast', 'coast'),
    ('clubs', 'glued'),
    ('holed', 'hones'),
    ('truce', 'crick'),
    ('plane', 'elite'),
    ('chino', 'tying'),
    ('frond', 'fresh'),
    ('grown', 'crows'),
    ('gleam', 'clear'),
    ('gyved', 'giver'),
    ('asked', 'enter'),
    ('skill', 'chili'),
    ('johns', 'print'),
    ('spend', 'shell'),
    ('train', 'draws'),
    ('bigot', 'began'),
    ('react', 'leech'),
    ('stubs', 'stars'),
    ('money', 'homed'),
    ('later', 'laxer'),
    ('talks', 'lacks'),
    ('scope', 'spent'),
    ('mirth', 'fifth'),
    ('farce', 'torts'),
    ('comes', 'bombs'),
    ('probe', 'shove'),
    ('bloke', 'grace'),
    ('order', 'aided'),
    ('spiny', 'spare'),
    ('champ', 'clash'),
    ('heave', 'leads'),
    ('wants', 'wakes'),
    ('spent', 'skill'),
    ('trail', 'trait'),
    ('petal', 'modal'),
    ('moved', 'bower'),
    ('tanks', 'calls'),
    ('ceder', 'coxes'),
    ('wades', 'facts'),
    ('paces', 'fasts'),
    ('wales', 'bales'),
    ('sales', 'balls'),
    ('stuck', 'shook'),
    ('spiff', 'scuff'),
    ('staff', 'spiff'),
    ('freed', 'creep'),
    ('dutch', 'hitch'),
    ('races', 'dates'),
    ('crams', 'clash'),
    ('break', 'creek'),
    ('roomy', 'hooks'),
    ('cream', 'tread'),
    ('corps', 'locks'),
    ('scoot', 'shock'),
    ('groan', 'brain'),
    ('shews', 'seems'),
    ('smack', 'stork'),
    ('chomp', 'crime'),
    ('words', 'perks'),
    ('firms', 'piled'),
    ('wonts', 'dorks'),
    ('guile', 'built'),
    ('tribe', 'bring'),
    ('clown', 'grows'),
    ('geeks', 'seeps'),
    ('phony', 'scope'),
    ('triad', 'freer'),
    ('trade', 'craze'),
    ('derby', 'heads'),
    ('staid', 'train'),
    ('chime', 'crept'),
    ('level', 'sever'),
    ('flout', 'blood'),
    ('knock', 'shock'),
    ('wordy', 'cards'),
    ('casts', 'porks'),
    ('levee', 'repel'),
    ('treat', 'tried'),
    ('stand', 'stunt'),
    ('shape', 'shaky'),
    ('hying', 'thing'),
    ('thing', 'vying'),
    ('sloth', 'plash'),
    ('thong', 'vying'),
    ('tough', 'cough'),
    ('snake', 'shave'),
    ('share', 'spank'),
    ('proxy', 'probe'),
    ('files', 'ailed'),
    ('peace', 'parch'),
    ('dough', 'rough'),
    ('dried', 'plied'),
    ('bench', 'lease'),
    ('duels', 'reels'),
    ('loped', 'wowed'),
    ('filed', 'abled'),
    ('prose', 'crone'),
    ('flesh', 'wroth'),
    ('sixth', 'salts'),
    ('prone', 'price'),
    ('wound', 'mound'),
    ('sabre', 'table'),
    ('sweat', 'sleep'),
    ('laced', 'waned'),
    ('hairy', 'dully'),
    ('rinds', 'kinds'),
    ('moves', 'cover'),
    ('tomes', 'voter'),
    ('feeds', 'herds'),
    ('shove', 'alone'),
    ('puree', 'cause'),
    ('beaks', 'means'),
    ('shots', 'shred'),
    ('hurry', 'carry'),
    ('slams', 'heads'),
    ('skeet', 'sleet'),
    ('sheet', 'sleep'),
    ('curvy', 'parry'),
    ('screw', 'throb'),
    ('sewer', 'lived'),
    ('fatal', 'decal'),
    ('spear', 'slept'),
    ('sowed', 'mowed'),
    ('floor', 'cloud'),
    ('tzars', 'reams')
]

DATE_LADDER_PAIRS = {
    '4/4/2022':{'start': 'calls', 'end': 'masks', 'sequence': 'calls, calms, calks, casks, masks'},
    '4/5/2022':{'start': 'crabs', 'end': 'brawn', 'sequence': 'crabs, craws, draws, drawn, brawn'},
    '4/6/2022':{'start': 'roots', 'end': 'words', 'sequence': 'roots, roofs, woofs, woods, words'},
    '4/7/2022':{'start': 'water', 'end': 'waded', 'sequence': 'water, wager, wages, wades, waded'},
    '4/8/2022':{'start': 'vanes', 'end': 'mimes', 'sequence': 'vanes, vines, tines, times, mimes'},
    '4/9/2022':{'start': 'after', 'end': 'pater', 'sequence': 'after, aster, ester, eater, pater'},
    '4/10/2022':{'start': 'shoat', 'end': 'store', 'sequence': 'shoat, shoot, short, shore, store'},
    '4/11/2022':{'start': 'nerds', 'end': 'beaus', 'sequence': 'nerds, herds, heads, beads, beaus'},
    '4/12/2022':{'start': 'likes', 'end': 'moved', 'sequence': 'likes, lives, loves, loved, moved'},
    '4/13/2022':{'start': 'miens', 'end': 'times', 'sequence': 'miens, liens, limns, limes, times'},
    '4/14/2022':{'start': 'chord', 'end': 'shorn', 'sequence': 'chord, chore, shore, short, shorn'},
    '4/15/2022':{'start': 'vanes', 'end': 'gazes', 'sequence': 'vanes, manes, mates, mazes, gazes'},
    '4/16/2022':{'start': 'mates', 'end': 'lambs', 'sequence': 'mates, makes, lakes, lames, lambs'},
    '4/17/2022':{'start': 'farce', 'end': 'north', 'sequence': 'farce, force, forte, forth, north'},
    '4/18/2022':{'start': 'hangs', 'end': 'binds', 'sequence': 'hangs, hands, hinds, rinds, binds'},
    '4/19/2022':{'start': 'smock', 'end': 'black', 'sequence': 'smock, smack, slack, clack, black'},
    '4/20/2022':{'start': 'drams', 'end': 'grain', 'sequence': 'drams, draws, drawn, drain, grain'},
    '4/21/2022':{'start': 'dries', 'end': 'cried', 'sequence': 'dries, bries, brier, crier, cried'},
    '4/22/2022':{'start': 'sighs', 'end': 'eight', 'sequence': 'sighs, sight, fight, light, eight'},
    '4/23/2022':{'start': 'emote', 'end': 'stoke', 'sequence': 'emote, smote, smoke, spoke, stoke'},
    '4/24/2022':{'start': 'flash', 'end': 'slush', 'sequence': 'flash, flesh, flush, plush, slush'},
    '4/25/2022':{'start': 'sheen', 'end': 'steel', 'sequence': 'sheen, sheer, steer, steed, steel'},
    '4/26/2022':{'start': 'train', 'end': 'braid', 'sequence': 'train, grain, drain, brain, braid'},
    '4/27/2022':{'start': 'crabs', 'end': 'ships', 'sequence': 'crabs, craps, chaps, chips, ships'},
    '4/28/2022':{'start': 'liege', 'end': 'mince', 'sequence': 'liege, siege, singe, since, mince'},
    '4/29/2022':{'start': 'slave', 'end': 'shape', 'sequence': 'slave, suave, stave, shave, shape'},
    '4/30/2022':{'start': 'leach', 'end': 'pease', 'sequence': 'leach, leash, least, lease, pease'},
    '5/1/2022':{'start': 'slush', 'end': 'frosh', 'sequence': 'slush, flush, flesh, fresh, frosh'},
    '5/2/2022':{'start': 'signs', 'end': 'bight', 'sequence': 'signs, sighs, sight, light, bight'},
    '5/3/2022':{'start': 'trout', 'end': 'greet', 'sequence': 'trout, grout, groat, great, greet'},
    '5/4/2022':{'start': 'spent', 'end': 'stone', 'sequence': 'spent, scent, scene, scone, stone'},
    '5/5/2022':{'start': 'liver', 'end': 'water', 'sequence': 'liver, laver, waver, wager, water'},
    '5/6/2022':{'start': 'count', 'end': 'sound', 'sequence': 'count, fount, found, bound, sound'},
    '5/7/2022':{'start': 'pines', 'end': 'liven', 'sequence': 'pines, lines, lined, lived, liven'},
    '5/8/2022':{'start': 'poses', 'end': 'ropes', 'sequence': 'poses, loses, roses, robes, ropes'},
    '5/9/2022':{'start': 'bruin', 'end': 'drain', 'sequence': 'bruin, brain, grain, train, drain'},
    '5/10/2022':{'start': 'smote', 'end': 'stele', 'sequence': 'smote, smoke, stoke, stole, stele'},
    '5/11/2022':{'start': 'beard', 'end': 'nears', 'sequence': 'beard, heard, heart, hears, nears'},
    '5/12/2022':{'start': 'bland', 'end': 'grins', 'sequence': 'bland, gland, grand, grind, grins'},
    '5/13/2022':{'start': 'witch', 'end': 'singe', 'sequence': 'witch, winch, wince, since, singe'},
    '5/14/2022':{'start': 'track', 'end': 'drank', 'sequence': 'track, truck, trunk, drunk, drank'},
    '5/15/2022':{'start': 'daisy', 'end': 'fairy', 'sequence': 'daisy, daily, dairy, hairy, fairy'},
    '5/16/2022':{'start': 'smoky', 'end': 'spake', 'sequence': 'smoky, smoke, spoke, spike, spake'},
    '5/17/2022':{'start': 'stair', 'end': 'stink', 'sequence': 'stair, staid, stand, stank, stink'},
    '5/18/2022':{'start': 'creed', 'end': 'dried', 'sequence': 'creed, cried, crier, drier, dried'},
    '5/19/2022':{'start': 'ester', 'end': 'hater', 'sequence': 'ester, eater, tater, water, hater'},
    '5/20/2022':{'start': 'sweep', 'end': 'sleet', 'sequence': 'sweep, sheep, sleep, sleek, sleet'},
    '5/21/2022':{'start': 'shack', 'end': 'black', 'sequence': 'shack, smack, snack, slack, black'},
    '5/22/2022':{'start': 'stork', 'end': 'stabs', 'sequence': 'stork, stark, start, stars, stabs'},
    '5/23/2022':{'start': 'johns', 'end': 'paint', 'sequence': 'johns, joins, joint, point, paint'},
    '5/24/2022':{'start': 'dyads', 'end': 'herds', 'sequence': 'dyads, deads, leads, heads, herds'},
    '5/25/2022':{'start': 'terms', 'end': 'earls', 'sequence': 'terms, terns, tarns, earns, earls'},
    '5/26/2022':{'start': 'chime', 'end': 'white', 'sequence': 'chime, chide, chine, whine, white'},
    '5/27/2022':{'start': 'stony', 'end': 'scent', 'sequence': 'stony, stone, scone, scene, scent'},
    '5/28/2022':{'start': 'casks', 'end': 'hosts', 'sequence': 'casks, casts, cysts, costs, hosts'},
    '5/29/2022':{'start': 'shirt', 'end': 'shall', 'sequence': 'shirt, shift, shaft, shalt, shall'},
    '5/30/2022':{'start': 'slunk', 'end': 'swine', 'sequence': 'slunk, slung, swung, swing, swine'},
    '5/31/2022':{'start': 'throb', 'end': 'screw', 'sequence': 'throb, throw, threw, shrew, screw'},
    '6/1/2022':{'start': 'creek', 'end': 'green', 'sequence': 'creek, greek, greed, greet, green'},
    '6/2/2022':{'start': 'trade', 'end': 'brick', 'sequence': 'trade, trace, track, trick, brick'},
    '6/3/2022':{'start': 'prosy', 'end': 'drone', 'sequence': 'prosy, prose, prove, drove, drone'},
    '6/4/2022':{'start': 'bring', 'end': 'prone', 'sequence': 'bring, wring, wrong, prong, prone'},
    '6/5/2022':{'start': 'chaff', 'end': 'charm', 'sequence': 'chaff, chafe, chase, chasm, charm'},
    '6/6/2022':{'start': 'couth', 'end': 'sooty', 'sequence': 'couth, mouth, south, sooth, sooty'},
    '6/7/2022':{'start': 'hanks', 'end': 'lends', 'sequence': 'hanks, hands, bands, lands, lends'},
    '6/8/2022':{'start': 'slide', 'end': 'spits', 'sequence': 'slide, slice, spice, spite, spits'},
    '6/9/2022':{'start': 'roger', 'end': 'tower', 'sequence': 'roger, rower, power, mower, tower'},
    '6/10/2022':{'start': 'wadis', 'end': 'wages', 'sequence': 'wadis, wades, wakes, waves, wages'},
    '6/11/2022':{'start': 'forth', 'end': 'corms', 'sequence': 'forth, forts, fores, forms, corms'},
    '6/12/2022':{'start': 'hands', 'end': 'rains', 'sequence': 'hands, rands, raids, rails, rains'},
    '6/13/2022':{'start': 'scull', 'end': 'swill', 'sequence': 'scull, skull, skill, still, swill'},
    '6/14/2022':{'start': 'groin', 'end': 'prows', 'sequence': 'groin, grown, grows, brows, prows'},
    '6/15/2022':{'start': 'moose', 'end': 'noise', 'sequence': 'moose, loose, goose, noose, noise'},
    '6/16/2022':{'start': 'horde', 'end': 'louse', 'sequence': 'horde, horse, house, youse, louse'},
    '6/17/2022':{'start': 'stony', 'end': 'stove', 'sequence': 'stony, stone, shone, shove, stove'},
    '6/18/2022':{'start': 'prink', 'end': 'taint', 'sequence': 'prink, print, point, paint, taint'},
    '6/19/2022':{'start': 'sherd', 'end': 'shark', 'sequence': 'sherd, shard, share, sharp, shark'},
    '6/20/2022':{'start': 'stung', 'end': 'swing', 'sequence': 'stung, swung, slung, sling, swing'},
    '6/21/2022':{'start': 'trail', 'end': 'drawn', 'sequence': 'trail, trait, train, drain, drawn'},
    '6/22/2022':{'start': 'leafs', 'end': 'heads', 'sequence': 'leafs, leads, deads, reads, heads'},
    '6/23/2022':{'start': 'weave', 'end': 'cease', 'sequence': 'weave, heave, leave, lease, cease'},
    '6/24/2022':{'start': 'shear', 'end': 'steak', 'sequence': 'shear, smear, spear, speak, steak'},
    '6/25/2022':{'start': 'rerun', 'end': 'woman', 'sequence': 'rerun, reran, reman, roman, woman'},
    '6/26/2022':{'start': 'depth', 'end': 'heats', 'sequence': 'depth, death, neath, heath, heats'},
    '6/27/2022':{'start': 'crits', 'end': 'write', 'sequence': 'crits, chits, whits, white, write'},
    '6/28/2022':{'start': 'heaps', 'end': 'gears', 'sequence': 'heaps, hears, years, nears, gears'},
    '6/29/2022':{'start': 'lower', 'end': 'borer', 'sequence': 'lower, tower, sower, bower, borer'},
    '6/30/2022':{'start': 'verse', 'end': 'chase', 'sequence': 'verse, terse, tease, cease, chase'},
    '7/1/2022':{'start': 'cello', 'end': 'palms', 'sequence': 'cello, cells, calls, calms, palms'},
    '7/2/2022':{'start': 'borer', 'end': 'bowed', 'sequence': 'borer, boxer, boxes, boxed, bowed'},
    '7/3/2022':{'start': 'spoke', 'end': 'whose', 'sequence': 'spoke, spore, shore, whore, whose'},
    '7/4/2022':{'start': 'lasts', 'end': 'faces', 'sequence': 'lasts, masts, fasts, facts, faces'},
    '7/5/2022':{'start': 'mixes', 'end': 'faxed', 'sequence': 'mixes, mixed, fixed, foxed, faxed'},
    '7/6/2022':{'start': 'dicks', 'end': 'porks', 'sequence': 'dicks, docks, dorks, works, porks'},
    '7/7/2022':{'start': 'chose', 'end': 'leash', 'sequence': 'chose, chase, cease, lease, leash'},
    '7/8/2022':{'start': 'bloom', 'end': 'eland', 'sequence': 'bloom, blood, blond, bland, eland'},
    '7/9/2022':{'start': 'ashes', 'end': 'askew', 'sequence': 'ashes, asses, assed, asked, askew'},
    '7/10/2022':{'start': 'tuans', 'end': 'terms', 'sequence': 'tuans, trans, trams, teams, terms'},
    '7/11/2022':{'start': 'stalk', 'end': 'shook', 'sequence': 'stalk, stack, stock, shock, shook'},
    '7/12/2022':{'start': 'hazes', 'end': 'rates', 'sequence': 'hazes, mazes, makes, mates, rates'},
    '7/13/2022':{'start': 'dimer', 'end': 'times', 'sequence': 'dimer, rimer, mimer, timer, times'},
    '7/14/2022':{'start': 'suits', 'end': 'saith', 'sequence': 'suits, suite, smite, smith, saith'},
    '7/15/2022':{'start': 'voice', 'end': 'tolls', 'sequence': 'voice, voile, toile, toils, tolls'},
    '7/16/2022':{'start': 'drank', 'end': 'think', 'sequence': 'drank, drunk, trunk, thunk, think'},
    '7/17/2022':{'start': 'graze', 'end': 'grove', 'sequence': 'graze, grade, grace, grave, grove'},
    '7/18/2022':{'start': 'whims', 'end': 'slips', 'sequence': 'whims, whirs, whips, ships, slips'},
    '7/19/2022':{'start': 'phone', 'end': 'prise', 'sequence': 'phone, prone, prove, prose, prise'},
    '7/20/2022':{'start': 'twain', 'end': 'draws', 'sequence': 'twain, train, drain, drawn, draws'},
    '7/21/2022':{'start': 'seize', 'end': 'stone', 'sequence': 'seize, seine, shine, shone, stone'},
    '7/22/2022':{'start': 'assed', 'end': 'aches', 'sequence': 'assed, asked, acked, ached, aches'},
    '7/23/2022':{'start': 'rover', 'end': 'tower', 'sequence': 'rover, lover, lower, bower, tower'},
    '7/24/2022':{'start': 'brawn', 'end': 'grown', 'sequence': 'brawn, prawn, drawn, drown, grown'},
    '7/25/2022':{'start': 'drank', 'end': 'think', 'sequence': 'drank, drunk, trunk, thunk, think'},
    '7/26/2022':{'start': 'works', 'end': 'morts', 'sequence': 'works, words, worts, ports, morts'},
    '7/27/2022':{'start': 'elate', 'end': 'stage', 'sequence': 'elate, slate, skate, state, stage'},
    '7/28/2022':{'start': 'wades', 'end': 'water', 'sequence': 'wades, waxes, wages, wager, water'},
    '7/29/2022':{'start': 'rowan', 'end': 'woken', 'sequence': 'rowan, roman, woman, women, woken'},
    '7/30/2022':{'start': 'corks', 'end': 'sorts', 'sequence': 'corks, forks, works, worts, sorts'},
    '7/31/2022':{'start': 'herds', 'end': 'keels', 'sequence': 'herds, heeds, heels, peels, keels'},
    '8/1/2022':{'start': 'spoke', 'end': 'shove', 'sequence': 'spoke, spore, snore, shore, shove'},
    '8/2/2022':{'start': 'start', 'end': 'store', 'sequence': 'start, stark, stork, story, store'},
    '8/3/2022':{'start': 'loins', 'end': 'think', 'sequence': 'loins, coins, chins, thins, think'},
    '8/4/2022':{'start': 'clash', 'end': 'plank', 'sequence': 'clash, flash, flask, flank, plank'},
    '8/5/2022':{'start': 'yeast', 'end': 'leans', 'sequence': 'yeast, least, leapt, leant, leans'},
    '8/6/2022':{'start': 'think', 'end': 'chide', 'sequence': 'think, thine, chine, chive, chide'},
    '8/7/2022':{'start': 'timid', 'end': 'wines', 'sequence': 'timid, timed, times, tines, wines'},
    '8/8/2022':{'start': 'close', 'end': 'chord', 'sequence': 'close, chose, choke, chore, chord'},
    '8/9/2022':{'start': 'gazes', 'end': 'vales', 'sequence': 'gazes, mazes, males, tales, vales'},
    '8/10/2022':{'start': 'needs', 'end': 'seedy', 'sequence': 'needs, heeds, deeds, seeds, seedy'},
    '8/11/2022':{'start': 'teach', 'end': 'couch', 'sequence': 'teach, reach, roach, coach, couch'},
    '8/12/2022':{'start': 'close', 'end': 'whoso', 'sequence': 'close, chose, those, whose, whoso'},
    '8/13/2022':{'start': 'stand', 'end': 'slain', 'sequence': 'stand, staid, stair, stain, slain'},
    '8/14/2022':{'start': 'crack', 'end': 'trick', 'sequence': 'crack, brack, brick, prick, trick'},
    '8/15/2022':{'start': 'cried', 'end': 'flues', 'sequence': 'cried, fried, fries, flies, flues'},
    '8/16/2022':{'start': 'pants', 'end': 'tarts', 'sequence': 'pants, parts, ports, torts, tarts'},
    '8/17/2022':{'start': 'truce', 'end': 'think', 'sequence': 'truce, trice, trick, thick, think'},
    '8/18/2022':{'start': 'thing', 'end': 'eying', 'sequence': 'thing, tying, vying, lying, eying'},
    '8/19/2022':{'start': 'works', 'end': 'hones', 'sequence': 'works, corks, conks, honks, hones'},
    '8/20/2022':{'start': 'shook', 'end': 'wrack', 'sequence': 'shook, shock, shack, whack, wrack'},
    '8/21/2022':{'start': 'heads', 'end': 'leant', 'sequence': 'heads, leads, leaps, leapt, leant'},
    '8/22/2022':{'start': 'signs', 'end': 'fight', 'sequence': 'signs, sighs, sight, tight, fight'},
    '8/23/2022':{'start': 'alder', 'end': 'ester', 'sequence': 'alder, alter, after, aster, ester'},
    '8/24/2022':{'start': 'bored', 'end': 'bands', 'sequence': 'bored, bores, bones, banes, bands'},
    '8/25/2022':{'start': 'still', 'end': 'stalk', 'sequence': 'still, stile, style, stale, stalk'},
    '8/26/2022':{'start': 'hills', 'end': 'files', 'sequence': 'hills, wills, fills, films, files'},
    '8/27/2022':{'start': 'goose', 'end': 'rouse', 'sequence': 'goose, moose, loose, louse, rouse'},
    '8/28/2022':{'start': 'yeast', 'end': 'toast', 'sequence': 'yeast, beast, blast, boast, toast'},
    '8/29/2022':{'start': 'drubs', 'end': 'glass', 'sequence': 'drubs, grubs, grabs, grass, glass'},
    '8/30/2022':{'start': 'dress', 'end': 'trees', 'sequence': 'dress, press, tress, trews, trees'},
    '8/31/2022':{'start': 'muons', 'end': 'leans', 'sequence': 'muons, moons, moans, means, leans'},
    '9/1/2022':{'start': 'frond', 'end': 'froth', 'sequence': 'frond, front, frost, frosh, froth'},
    '9/2/2022':{'start': 'couth', 'end': 'month', 'sequence': 'couth, youth, south, mouth, month'},
    '9/3/2022':{'start': 'spend', 'end': 'steal', 'sequence': 'spend, speed, steed, stead, steal'},
    '9/4/2022':{'start': 'dimes', 'end': 'jilts', 'sequence': 'dimes, times, tiles, tilts, jilts'},
    '9/5/2022':{'start': 'faith', 'end': 'smile', 'sequence': 'faith, saith, smith, smite, smile'},
    '9/6/2022':{'start': 'snare', 'end': 'shake', 'sequence': 'snare, snake, stake, slake, shake'},
    '9/7/2022':{'start': 'smoky', 'end': 'spice', 'sequence': 'smoky, smoke, spoke, spike, spice'},
    '9/8/2022':{'start': 'dutch', 'end': 'pitch', 'sequence': 'dutch, ditch, witch, aitch, pitch'},
    '9/9/2022':{'start': 'kerbs', 'end': 'meads', 'sequence': 'kerbs, herbs, herds, heads, meads'},
    '9/10/2022':{'start': 'prowl', 'end': 'brown', 'sequence': 'prowl, growl, grown, drown, brown'},
    '9/11/2022':{'start': 'cinch', 'end': 'since', 'sequence': 'cinch, winch, wince, mince, since'},
    '9/12/2022':{'start': 'flash', 'end': 'frost', 'sequence': 'flash, flesh, fresh, frosh, frost'},
    '9/13/2022':{'start': 'pence', 'end': 'plant', 'sequence': 'pence, peace, place, plane, plant'},
    '9/14/2022':{'start': 'scout', 'end': 'abort', 'sequence': 'scout, spout, sport, aport, abort'},
    '9/15/2022':{'start': 'hands', 'end': 'mains', 'sequence': 'hands, rands, raids, maids, mains'},
    '9/16/2022':{'start': 'gazer', 'end': 'names', 'sequence': 'gazer, gazed, gamed, named, names'},
    '9/17/2022':{'start': 'works', 'end': 'forma', 'sequence': 'works, corks, forks, forms, forma'},
    '9/18/2022':{'start': 'douse', 'end': 'goose', 'sequence': 'douse, mouse, moose, noose, goose'},
    '9/19/2022':{'start': 'great', 'end': 'brown', 'sequence': 'great, groat, groan, grown, brown'},
    '9/20/2022':{'start': 'baler', 'end': 'water', 'sequence': 'baler, baker, waker, wader, water'},
    '9/21/2022':{'start': 'kinds', 'end': 'lined', 'sequence': 'kinds, winds, wines, lines, lined'},
    '9/22/2022':{'start': 'often', 'end': 'eaten', 'sequence': 'often, outen, oaten, paten, eaten'},
    '9/23/2022':{'start': 'burst', 'end': 'worse', 'sequence': 'burst, durst, wurst, worst, worse'},
    '9/24/2022':{'start': 'dimer', 'end': 'gives', 'sequence': 'dimer, diver, giver, given, gives'},
    '9/25/2022':{'start': 'preen', 'end': 'creed', 'sequence': 'preen, green, greet, greed, creed'},
    '9/26/2022':{'start': 'blond', 'end': 'clank', 'sequence': 'blond, blind, bland, blank, clank'},
    '9/27/2022':{'start': 'honey', 'end': 'boned', 'sequence': 'honey, money, coney, coned, boned'},
    '9/28/2022':{'start': 'loves', 'end': 'fiver', 'sequence': 'loves, lover, rover, river, fiver'},
    '9/29/2022':{'start': 'drown', 'end': 'groat', 'sequence': 'drown, crown, grown, groan, groat'},
    '9/30/2022':{'start': 'darns', 'end': 'cases', 'sequence': 'darns, darts, carts, casts, cases'},
    '10/1/2022':{'start': 'tweed', 'end': 'sleep', 'sequence': 'tweed, tweet, sweet, sweep, sleep'},
    '10/2/2022':{'start': 'spear', 'end': 'sweat', 'sequence': 'spear, smear, shear, swear, sweat'},
    '10/3/2022':{'start': 'wring', 'end': 'phone', 'sequence': 'wring, wrong, prong, prone, phone'},
    '10/4/2022':{'start': 'march', 'end': 'ditch', 'sequence': 'march, match, watch, witch, ditch'},
    '10/5/2022':{'start': 'roofs', 'end': 'moons', 'sequence': 'roofs, roods, woods, moods, moons'},
    '10/6/2022':{'start': 'spell', 'end': 'stall', 'sequence': 'spell, swell, smell, small, stall'},
    '10/7/2022':{'start': 'found', 'end': 'mount', 'sequence': 'found, sound, pound, mound, mount'},
    '10/8/2022':{'start': 'check', 'end': 'sheep', 'sequence': 'check, cheek, cheer, cheep, sheep'},
    '10/9/2022':{'start': 'leant', 'end': 'heist', 'sequence': 'leant, least, feast, feist, heist'},
    '10/10/2022':{'start': 'spilt', 'end': 'skull', 'sequence': 'spilt, spill, still, skill, skull'},
    '10/11/2022':{'start': 'oaten', 'end': 'offer', 'sequence': 'oaten, outen, often, offen, offer'},
    '10/12/2022':{'start': 'chews', 'end': 'crown', 'sequence': 'chews, crews, crows, crowd, crown'},
    '10/13/2022':{'start': 'brain', 'end': 'trait', 'sequence': 'brain, grain, grail, trail, trait'},
    '10/14/2022':{'start': 'imply', 'end': 'ample', 'sequence': 'imply, amply, apply, apple, ample'},
    '10/15/2022':{'start': 'prate', 'end': 'brave', 'sequence': 'prate, orate, grate, grave, brave'},
    '10/16/2022':{'start': 'flats', 'end': 'board', 'sequence': 'flats, blats, boats, boars, board'},
    '10/17/2022':{'start': 'steel', 'end': 'skeet', 'sequence': 'steel, steer, sheer, sheet, skeet'},
    '10/18/2022':{'start': 'whomp', 'end': 'whose', 'sequence': 'whomp, whoop, whooo, whoso, whose'},
    '10/19/2022':{'start': 'cargo', 'end': 'badge', 'sequence': 'cargo, largo, large, barge, badge'},
    '10/20/2022':{'start': 'holds', 'end': 'wards', 'sequence': 'holds, folds, fords, words, wards'},
    '10/21/2022':{'start': 'spots', 'end': 'shoot', 'sequence': 'spots, shots, shoes, shoos, shoot'},
    '10/22/2022':{'start': 'scare', 'end': 'shake', 'sequence': 'scare, scale, shale, shape, shake'},
    '10/23/2022':{'start': 'brews', 'end': 'drown', 'sequence': 'brews, brows, brown, frown, drown'},
    '10/24/2022':{'start': 'gleam', 'end': 'clear', 'sequence': 'gleam, glean, clean, cleat, clear'},
    '10/25/2022':{'start': 'grain', 'end': 'bruit', 'sequence': 'grain, train, brain, bruin, bruit'},
    '10/26/2022':{'start': 'whiny', 'end': 'think', 'sequence': 'whiny, whine, thine, thins, think'},
    '10/27/2022':{'start': 'stoae', 'end': 'smoke', 'sequence': 'stoae, stone, stove, stoke, smoke'},
    '10/28/2022':{'start': 'taint', 'end': 'fling', 'sequence': 'taint, paint, faint, flint, fling'},
    '10/29/2022':{'start': 'sweep', 'end': 'swept', 'sequence': 'sweep, sleep, sleet, slept, swept'},
    '10/30/2022':{'start': 'flair', 'end': 'train', 'sequence': 'flair, flail, frail, trail, train'},
    '10/31/2022':{'start': 'white', 'end': 'watts', 'sequence': 'white, write, writs, waits, watts'},
    '11/1/2022':{'start': 'sharp', 'end': 'snare', 'sequence': 'sharp, scarp, scare, stare, snare'},
    '11/2/2022':{'start': 'arose', 'end': 'trove', 'sequence': 'arose, prose, prone, prove, trove'},
    '11/3/2022':{'start': 'brats', 'end': 'moans', 'sequence': 'brats, blats, boats, moats, moans'},
    '11/4/2022':{'start': 'scent', 'end': 'smell', 'sequence': 'scent, spent, spelt, smelt, smell'},
    '11/5/2022':{'start': 'tying', 'end': 'thees', 'sequence': 'tying, thing, thins, thens, thees'},
    '11/6/2022':{'start': 'assed', 'end': 'ached', 'sequence': 'assed, asked, acked, acted, ached'},
    '11/7/2022':{'start': 'works', 'end': 'booky', 'sequence': 'works, corks, cooks, cooky, booky'},
    '11/8/2022':{'start': 'woman', 'end': 'token', 'sequence': 'woman, women, woven, woken, token'},
    '11/9/2022':{'start': 'drunk', 'end': 'frank', 'sequence': 'drunk, drink, prink, prank, frank'},
    '11/10/2022':{'start': 'knobs', 'end': 'snowy', 'sequence': 'knobs, knops, knows, snows, snowy'},
    '11/11/2022':{'start': 'dreck', 'end': 'break', 'sequence': 'dreck, wreck, wreak, freak, break'},
    '11/12/2022':{'start': 'spore', 'end': 'stoae', 'sequence': 'spore, spoke, stoke, stove, stoae'},
    '11/13/2022':{'start': 'bench', 'end': 'leach', 'sequence': 'bench, beach, beech, leech, leach'},
    '11/14/2022':{'start': 'nares', 'end': 'makes', 'sequence': 'nares, tares, tales, males, makes'},
    '11/15/2022':{'start': 'class', 'end': 'grabs', 'sequence': 'class, glass, grass, grays, grabs'},
    '11/16/2022':{'start': 'bries', 'end': 'tried', 'sequence': 'bries, dries, cries, cried, tried'},
    '11/17/2022':{'start': 'treap', 'end': 'gloat', 'sequence': 'treap, treat, great, groat, gloat'},
    '11/18/2022':{'start': 'roust', 'end': 'house', 'sequence': 'roust, rouse, louse, mouse, house'},
    '11/19/2022':{'start': 'aider', 'end': 'after', 'sequence': 'aider, adder, alder, alter, after'},
    '11/20/2022':{'start': 'rhyme', 'end': 'where', 'sequence': 'rhyme, thyme, theme, there, where'},
    '11/21/2022':{'start': 'owing', 'end': 'brick', 'sequence': 'owing, oring, bring, brink, brick'},
    '11/22/2022':{'start': 'elves', 'end': 'caved', 'sequence': 'elves, eaves, saves, saved, caved'},
    '11/23/2022':{'start': 'croon', 'end': 'drawl', 'sequence': 'croon, crown, drown, drawn, drawl'},
    '11/24/2022':{'start': 'therm', 'end': 'shore', 'sequence': 'therm, there, where, whore, shore'},
    '11/25/2022':{'start': 'oiler', 'end': 'times', 'sequence': 'oiler, tiler, tiger, timer, times'},
    '11/26/2022':{'start': 'nooks', 'end': 'booms', 'sequence': 'nooks, cooks, books, boobs, booms'},
    '11/27/2022':{'start': 'heaps', 'end': 'peals', 'sequence': 'heaps, heads, reads, reals, peals'},
    '11/28/2022':{'start': 'sends', 'end': 'weeds', 'sequence': 'sends, seeds, needs, heeds, weeds'},
    '11/29/2022':{'start': 'wheat', 'end': 'where', 'sequence': 'wheat, wheal, wheel, wheee, where'},
    '11/30/2022':{'start': 'shawm', 'end': 'shape', 'sequence': 'shawm, shawl, shall, shale, shape'},
    '12/1/2022':{'start': 'elate', 'end': 'peace', 'sequence': 'elate, slate, plate, place, peace'},
    '12/2/2022':{'start': 'black', 'end': 'trace', 'sequence': 'black, brack, wrack, track, trace'},
    '12/3/2022':{'start': 'holer', 'end': 'loves', 'sequence': 'holer, hover, lover, loved, loves'},
    '12/4/2022':{'start': 'offen', 'end': 'eaten', 'sequence': 'offen, often, outen, oaten, eaten'},
    '12/5/2022':{'start': 'whose', 'end': 'shore', 'sequence': 'whose, chose, choke, chore, shore'},
    '12/6/2022':{'start': 'foxes', 'end': 'lower', 'sequence': 'foxes, boxes, boxer, bower, lower'},
    '12/7/2022':{'start': 'while', 'end': 'chill', 'sequence': 'while, chile, child, chili, chill'},
    '12/8/2022':{'start': 'ships', 'end': 'chops', 'sequence': 'ships, whips, chips, chaps, chops'},
    '12/9/2022':{'start': 'feuds', 'end': 'needs', 'sequence': 'feuds, feeds, weeds, reeds, needs'},
    '12/10/2022':{'start': 'gland', 'end': 'brain', 'sequence': 'gland, grand, brand, braid, brain'},
    '12/11/2022':{'start': 'drank', 'end': 'point', 'sequence': 'drank, drink, prink, print, point'},
    '12/12/2022':{'start': 'spite', 'end': 'stake', 'sequence': 'spite, spine, spike, spake, stake'},
    '12/13/2022':{'start': 'crack', 'end': 'brace', 'sequence': 'crack, wrack, track, brack, brace'},
    '12/14/2022':{'start': 'crime', 'end': 'slily', 'sequence': 'crime, clime, slime, slimy, slily'},
    '12/15/2022':{'start': 'crave', 'end': 'grapy', 'sequence': 'crave, brave, grave, gravy, grapy'},
    '12/16/2022':{'start': 'freak', 'end': 'brack', 'sequence': 'freak, wreak, wreck, wrack, brack'},
    '12/17/2022':{'start': 'drunk', 'end': 'blink', 'sequence': 'drunk, drank, drink, brink, blink'},
    '12/18/2022':{'start': 'agony', 'end': 'clone', 'sequence': 'agony, agone, atone, alone, clone'},
    '12/19/2022':{'start': 'skies', 'end': 'shuts', 'sequence': 'skies, shies, ships, shits, shuts'},
    '12/20/2022':{'start': 'there', 'end': 'choke', 'sequence': 'there, where, whore, chore, choke'},
    '12/21/2022':{'start': 'lardy', 'end': 'hanks', 'sequence': 'lardy, hardy, handy, hands, hanks'},
    '12/22/2022':{'start': 'given', 'end': 'miser', 'sequence': 'given, giver, river, riser, miser'},
    '12/23/2022':{'start': 'boast', 'end': 'leant', 'sequence': 'boast, beast, feast, least, leant'},
    '12/24/2022':{'start': 'beast', 'end': 'leans', 'sequence': 'beast, least, leapt, leant, leans'},
    '12/25/2022':{'start': 'stout', 'end': 'shoot', 'sequence': 'stout, scout, snout, shout, shoot'},
    '12/26/2022':{'start': 'wince', 'end': 'tinge', 'sequence': 'wince, mince, since, singe, tinge'},
    '12/27/2022':{'start': 'seems', 'end': 'peeps', 'sequence': 'seems, stems, steps, seeps, peeps'},
    '12/28/2022':{'start': 'alone', 'end': 'stoae', 'sequence': 'alone, atone, stone, stove, stoae'},
    '12/29/2022':{'start': 'seers', 'end': 'diems', 'sequence': 'seers, seeks, seems, deems, diems'},
    '12/30/2022':{'start': 'print', 'end': 'saint', 'sequence': 'print, point, paint, faint, saint'},
    '12/31/2022':{'start': 'upend', 'end': 'scant', 'sequence': 'upend, spend, spent, scent, scant'},
    '1/1/2023':{'start': 'dress', 'end': 'trees', 'sequence': 'dress, press, tress, treys, trees'},
    '1/2/2023':{'start': 'sneer', 'end': 'swear', 'sequence': 'sneer, steer, sheer, shear, swear'},
    '1/3/2023':{'start': 'borer', 'end': 'makes', 'sequence': 'borer, barer, baker, bakes, makes'},
    '1/4/2023':{'start': 'groan', 'end': 'frail', 'sequence': 'groan, groin, grain, grail, frail'},
    '1/5/2023':{'start': 'order', 'end': 'elder', 'sequence': 'order, odder, older, alder, elder'},
    '1/6/2023':{'start': 'shore', 'end': 'scene', 'sequence': 'shore, shove, shone, scone, scene'},
    '1/7/2023':{'start': 'fount', 'end': 'hound', 'sequence': 'fount, found, round, mound, hound'},
    '1/8/2023':{'start': 'sires', 'end': 'times', 'sequence': 'sires, mires, mixes, mimes, times'},
    '1/9/2023':{'start': 'could', 'end': 'mound', 'sequence': 'could, would, wound, found, mound'},
    '1/10/2023':{'start': 'whomp', 'end': 'whose', 'sequence': 'whomp, whoop, whooo, whoso, whose'},
    '1/11/2023':{'start': 'fears', 'end': 'seams', 'sequence': 'fears, tears, gears, sears, seams'},
    '1/12/2023':{'start': 'sighs', 'end': 'bight', 'sequence': 'sighs, sight, right, light, bight'},
    '1/13/2023':{'start': 'spike', 'end': 'spare', 'sequence': 'spike, spice, spine, spire, spare'},
    '1/14/2023':{'start': 'beamy', 'end': 'seeps', 'sequence': 'beamy, seamy, seams, seems, seeps'},
    '1/15/2023':{'start': 'brain', 'end': 'flail', 'sequence': 'brain, grain, grail, frail, flail'},
    '1/16/2023':{'start': 'shave', 'end': 'state', 'sequence': 'shave, suave, stave, stale, state'},
    '1/17/2023':{'start': 'clove', 'end': 'prove', 'sequence': 'clove, glove, grove, drove, prove'},
    '1/18/2023':{'start': 'nosey', 'end': 'honey', 'sequence': 'nosey, mosey, money, coney, honey'},
    '1/19/2023':{'start': 'toast', 'end': 'roost', 'sequence': 'toast, boast, coast, roast, roost'},
    '1/20/2023':{'start': 'sweat', 'end': 'sheep', 'sequence': 'sweat, sweet, sweep, steep, sheep'},
    '1/21/2023':{'start': 'fiats', 'end': 'coats', 'sequence': 'fiats, frats, brats, boats, coats'},
    '1/22/2023':{'start': 'scour', 'end': 'snort', 'sequence': 'scour, scout, shout, short, snort'},
    '1/23/2023':{'start': 'leaps', 'end': 'least', 'sequence': 'leaps, leaks, leans, leant, least'},
    '1/24/2023':{'start': 'blink', 'end': 'plans', 'sequence': 'blink, blank, plank, plant, plans'},
    '1/25/2023':{'start': 'deist', 'end': 'beast', 'sequence': 'deist, feist, feast, least, beast'},
    '1/26/2023':{'start': 'agone', 'end': 'crony', 'sequence': 'agone, alone, clone, crone, crony'},
    '1/27/2023':{'start': 'upend', 'end': 'spies', 'sequence': 'upend, spend, speed, spied, spies'},
    '1/28/2023':{'start': 'hemps', 'end': 'heart', 'sequence': 'hemps, heaps, heads, hears, heart'},
    '1/29/2023':{'start': 'sands', 'end': 'wends', 'sequence': 'sands, lands, hands, wands, wends'},
    '1/30/2023':{'start': 'yeast', 'end': 'beaux', 'sequence': 'yeast, least, beast, beaut, beaux'},
    '1/31/2023':{'start': 'stick', 'end': 'slack', 'sequence': 'stick, stuck, stock, stack, slack'},
    '2/1/2023':{'start': 'joins', 'end': 'prink', 'sequence': 'joins, joint, point, print, prink'},
    '2/2/2023':{'start': 'slept', 'end': 'sweep', 'sequence': 'slept, sleet, sleek, sleep, sweep'},
    '2/3/2023':{'start': 'savor', 'end': 'pater', 'sequence': 'savor, saver, waver, water, pater'},
    '2/4/2023':{'start': 'wordy', 'end': 'corms', 'sequence': 'wordy, words, cords, corks, corms'},
    '2/5/2023':{'start': 'whomp', 'end': 'whose', 'sequence': 'whomp, whoop, whooo, whoso, whose'},
    '2/6/2023':{'start': 'faith', 'end': 'suite', 'sequence': 'faith, saith, smith, smite, suite'},
    '2/7/2023':{'start': 'livid', 'end': 'wines', 'sequence': 'livid, lived, lined, wined, wines'},
    '2/8/2023':{'start': 'given', 'end': 'liver', 'sequence': 'given, liven, riven, river, liver'},
    '2/9/2023':{'start': 'trick', 'end': 'thanx', 'sequence': 'trick, thick, think, thank, thanx'},
    '2/10/2023':{'start': 'point', 'end': 'heist', 'sequence': 'point, joint, joist, hoist, heist'},
    '2/11/2023':{'start': 'stern', 'end': 'swain', 'sequence': 'stern, stein, stain, slain, swain'},
    '2/12/2023':{'start': 'tombs', 'end': 'domes', 'sequence': 'tombs, combs, comas, comes, domes'},
    '2/13/2023':{'start': 'nerds', 'end': 'woods', 'sequence': 'nerds, nards, wards, words, woods'},
    '2/14/2023':{'start': 'stout', 'end': 'sport', 'sequence': 'stout, snout, snoot, snort, sport'},
    '2/15/2023':{'start': 'snood', 'end': 'scoop', 'sequence': 'snood, stood, stool, stoop, scoop'},
    '2/16/2023':{'start': 'tales', 'end': 'maces', 'sequence': 'tales, males, mates, mazes, maces'},
    '2/17/2023':{'start': 'taken', 'end': 'waked', 'sequence': 'taken, token, woken, waken, waked'},
    '2/18/2023':{'start': 'heads', 'end': 'means', 'sequence': 'heads, leads, deads, deans, means'},
    '2/19/2023':{'start': 'saved', 'end': 'eaves', 'sequence': 'saved, saves, waves, paves, eaves'},
    '2/20/2023':{'start': 'groat', 'end': 'tread', 'sequence': 'groat, great, treat, treap, tread'},
    '2/21/2023':{'start': 'mikes', 'end': 'poses', 'sequence': 'mikes, miles, piles, poles, poses'},
    '2/22/2023':{'start': 'house', 'end': 'roost', 'sequence': 'house, rouse, roust, roast, roost'},
    '2/23/2023':{'start': 'wreak', 'end': 'creep', 'sequence': 'wreak, break, creak, creek, creep'},
    '2/24/2023':{'start': 'blond', 'end': 'vroom', 'sequence': 'blond, blood, brood, broom, vroom'},
    '2/25/2023':{'start': 'maces', 'end': 'tikes', 'sequence': 'maces, males, makes, takes, tikes'},
    '2/26/2023':{'start': 'emote', 'end': 'stoke', 'sequence': 'emote, smote, smoke, spoke, stoke'},
    '2/27/2023':{'start': 'forth', 'end': 'pouts', 'sequence': 'forth, forte, forts, ports, pouts'},
    '2/28/2023':{'start': 'court', 'end': 'pound', 'sequence': 'court, count, mount, mound, pound'},
    '3/1/2023':{'start': 'cheat', 'end': 'crepe', 'sequence': 'cheat, chest, crest, crept, crepe'},
    '3/2/2023':{'start': 'leash', 'end': 'yeast', 'sequence': 'leash, lease, least, feast, yeast'},
    '3/3/2023':{'start': 'whose', 'end': 'theme', 'sequence': 'whose, chose, those, these, theme'},
    '3/4/2023':{'start': 'truce', 'end': 'think', 'sequence': 'truce, truck, trick, thick, think'},
    '3/5/2023':{'start': 'porks', 'end': 'copes', 'sequence': 'porks, works, corks, cores, copes'},
    '3/6/2023':{'start': 'clone', 'end': 'chase', 'sequence': 'clone, clove, close, chose, chase'},
    '3/7/2023':{'start': 'could', 'end': 'count', 'sequence': 'could, mould, moult, mount, count'},
    '3/8/2023':{'start': 'meant', 'end': 'grads', 'sequence': 'meant, means, meads, mrads, grads'},
    '3/9/2023':{'start': 'creak', 'end': 'bread', 'sequence': 'creak, wreak, freak, break, bread'},
    '3/10/2023':{'start': 'wheys', 'end': 'white', 'sequence': 'wheys, whets, whats, whits, white'},
    '3/11/2023':{'start': 'rhyme', 'end': 'these', 'sequence': 'rhyme, thyme, theme, there, these'},
    '3/12/2023':{'start': 'price', 'end': 'track', 'sequence': 'price, prick, crick, trick, track'},
    '3/13/2023':{'start': 'hound', 'end': 'moult', 'sequence': 'hound, wound, would, mould, moult'},
    '3/14/2023':{'start': 'pater', 'end': 'lager', 'sequence': 'pater, water, wader, wager, lager'},
    '3/15/2023':{'start': 'conks', 'end': 'comer', 'sequence': 'conks, cones, comes, comet, comer'},
    '3/16/2023':{'start': 'adder', 'end': 'sided', 'sequence': 'adder, added, anded, aided, sided'},
    '3/17/2023':{'start': 'place', 'end': 'tench', 'sequence': 'place, peace, peach, teach, tench'},
    '3/18/2023':{'start': 'heard', 'end': 'bears', 'sequence': 'heard, heart, hears, fears, bears'},
    '3/19/2023':{'start': 'boats', 'end': 'zooms', 'sequence': 'boats, boots, boors, booms, zooms'},
    '3/20/2023':{'start': 'cargo', 'end': 'mange', 'sequence': 'cargo, largo, large, marge, mange'},
    '3/21/2023':{'start': 'youse', 'end': 'lousy', 'sequence': 'youse, house, mouse, mousy, lousy'},
    '3/22/2023':{'start': 'sleet', 'end': 'sheer', 'sequence': 'sleet, sweet, skeet, sheet, sheer'},
    '3/23/2023':{'start': 'prose', 'end': 'gripe', 'sequence': 'prose, prove, grove, grope, gripe'},
    '3/24/2023':{'start': 'reeds', 'end': 'hells', 'sequence': 'reeds, heeds, heads, heals, hells'},
    '3/25/2023':{'start': 'breed', 'end': 'blind', 'sequence': 'breed, bleed, blend, blond, blind'},
    '3/26/2023':{'start': 'helps', 'end': 'dears', 'sequence': 'helps, heaps, hears, bears, dears'},
    '3/27/2023':{'start': 'germs', 'end': 'peeks', 'sequence': 'germs, terms, perms, perks, peeks'},
    '3/28/2023':{'start': 'halls', 'end': 'vails', 'sequence': 'halls, walls, wails, nails, vails'},
    '3/29/2023':{'start': 'smoky', 'end': 'smith', 'sequence': 'smoky, smoke, smote, smite, smith'},
    '3/30/2023':{'start': 'cheap', 'end': 'clean', 'sequence': 'cheap, cheat, cleat, clear, clean'},
    '3/31/2023':{'start': 'groin', 'end': 'braid', 'sequence': 'groin, grain, drain, brain, braid'},
    '4/1/2023':{'start': 'lousy', 'end': 'goose', 'sequence': 'lousy, mousy, mouse, moose, goose'},
    '4/2/2023':{'start': 'seats', 'end': 'years', 'sequence': 'seats, heats, hears, gears, years'},
    '4/3/2023':{'start': 'shawm', 'end': 'shill', 'sequence': 'shawm, shawl, shall, shell, shill'},
    '4/4/2023':{'start': 'stood', 'end': 'spoon', 'sequence': 'stood, stoop, stool, spool, spoon'},
    '4/5/2023':{'start': 'phone', 'end': 'wrung', 'sequence': 'phone, prone, prong, wrong, wrung'},
    '4/6/2023':{'start': 'since', 'end': 'witch', 'sequence': 'since, mince, wince, winch, witch'},
    '4/7/2023':{'start': 'corms', 'end': 'woods', 'sequence': 'corms, worms, words, wolds, woods'},
    '4/8/2023':{'start': 'chits', 'end': 'think', 'sequence': 'chits, chins, chino, chink, think'},
    '4/9/2023':{'start': 'gayly', 'end': 'dairy', 'sequence': 'gayly, gaily, daily, daisy, dairy'},
    '4/10/2023':{'start': 'clung', 'end': 'blink', 'sequence': 'clung, cling, sling, slink, blink'},
    '4/11/2023':{'start': 'waned', 'end': 'raves', 'sequence': 'waned, waled, waved, waves, raves'},
    '4/12/2023':{'start': 'swift', 'end': 'shoat', 'sequence': 'swift, shift, shirt, short, shoat'},
    '4/13/2023':{'start': 'shawm', 'end': 'small', 'sequence': 'shawm, shawl, shall, stall, small'},
    '4/14/2023':{'start': 'loams', 'end': 'weans', 'sequence': 'loams, loans, leans, means, weans'},
    '4/15/2023':{'start': 'stats', 'end': 'scare', 'sequence': 'stats, state, stale, scale, scare'},
    '4/16/2023':{'start': 'short', 'end': 'snoop', 'sequence': 'short, shoot, snoot, snood, snoop'},
    '4/17/2023':{'start': 'slept', 'end': 'sleek', 'sequence': 'slept, swept, sweet, sleet, sleek'},
    '4/18/2023':{'start': 'forth', 'end': 'words', 'sequence': 'forth, forts, fords, lords, words'},
    '4/19/2023':{'start': 'foods', 'end': 'boots', 'sequence': 'foods, roods, roofs, roots, boots'},
    '4/20/2023':{'start': 'wards', 'end': 'goods', 'sequence': 'wards, words, woods, roods, goods'},
    '4/21/2023':{'start': 'rowan', 'end': 'woken', 'sequence': 'rowan, roman, woman, women, woken'},
    '4/22/2023':{'start': 'whale', 'end': 'wrote', 'sequence': 'whale, while, white, write, wrote'},
    '4/23/2023':{'start': 'assed', 'end': 'alter', 'sequence': 'assed, asked, asker, aster, alter'},
    '4/24/2023':{'start': 'trick', 'end': 'blank', 'sequence': 'trick, track, brack, black, blank'},
    '4/25/2023':{'start': 'dwelt', 'end': 'smell', 'sequence': 'dwelt, dwell, swell, shell, smell'},
    '4/26/2023':{'start': 'anted', 'end': 'aides', 'sequence': 'anted, anded, added, aided, aides'},
    '4/27/2023':{'start': 'carts', 'end': 'pares', 'sequence': 'carts, parts, pacts, paces, pares'},
    '4/28/2023':{'start': 'shill', 'end': 'stele', 'sequence': 'shill, swill, still, stile, stele'},
    '4/29/2023':{'start': 'blood', 'end': 'vroom', 'sequence': 'blood, bloom, gloom, groom, vroom'},
    '4/30/2023':{'start': 'parse', 'end': 'crust', 'sequence': 'parse, pause, cause, cruse, crust'},
    '5/1/2023':{'start': 'scorn', 'end': 'sward', 'sequence': 'scorn, sworn, swore, sword, sward'},
    '5/2/2023':{'start': 'merge', 'end': 'large', 'sequence': 'merge, marge, sarge, barge, large'},
    '5/3/2023':{'start': 'share', 'end': 'snarl', 'sequence': 'share, sharp, shark, snark, snarl'},
    '5/4/2023':{'start': 'clave', 'end': 'whose', 'sequence': 'clave, clove, close, chose, whose'},
    '5/5/2023':{'start': 'swore', 'end': 'snake', 'sequence': 'swore, store, stoke, stake, snake'},
    '5/6/2023':{'start': 'folks', 'end': 'hoods', 'sequence': 'folks, folds, colds, holds, hoods'},
    '5/7/2023':{'start': 'braze', 'end': 'grate', 'sequence': 'braze, brake, brave, grave, grate'},
    '5/8/2023':{'start': 'worth', 'end': 'worry', 'sequence': 'worth, worts, words, wordy, worry'},
    '5/9/2023':{'start': 'aleck', 'end': 'flack', 'sequence': 'aleck, alack, black, clack, flack'},
    '5/10/2023':{'start': 'plump', 'end': 'stamp', 'sequence': 'plump, clump, slump, stump, stamp'},
    '5/11/2023':{'start': 'wrier', 'end': 'creed', 'sequence': 'wrier, drier, crier, cried, creed'},
    '5/12/2023':{'start': 'leach', 'end': 'wench', 'sequence': 'leach, reach, beach, bench, wench'},
    '5/13/2023':{'start': 'start', 'end': 'stags', 'sequence': 'start, stare, stage, stagy, stags'},
    '5/14/2023':{'start': 'razes', 'end': 'pages', 'sequence': 'razes, races, faces, paces, pages'},
    '5/15/2023':{'start': 'hence', 'end': 'since', 'sequence': 'hence, henge, hinge, singe, since'},
    '5/16/2023':{'start': 'arced', 'end': 'added', 'sequence': 'arced, armed, aimed, aided, added'},
    '5/17/2023':{'start': 'handy', 'end': 'merry', 'sequence': 'handy, hardy, harry, marry, merry'},
    '5/18/2023':{'start': 'spoil', 'end': 'shock', 'sequence': 'spoil, spool, spook, shook, shock'},
    '5/19/2023':{'start': 'spoke', 'end': 'snore', 'sequence': 'spoke, smoke, stoke, store, snore'},
    '5/20/2023':{'start': 'drunk', 'end': 'brick', 'sequence': 'drunk, drink, prink, prick, brick'},
    '5/21/2023':{'start': 'bigot', 'end': 'right', 'sequence': 'bigot, bight, night, might, right'},
    '5/22/2023':{'start': 'march', 'end': 'batch', 'sequence': 'march, match, catch, natch, batch'},
    '5/23/2023':{'start': 'begun', 'end': 'begot', 'sequence': 'begun, begin, began, begat, begot'},
    '5/24/2023':{'start': 'seers', 'end': 'stems', 'sequence': 'seers, seeks, seeps, steps, stems'},
    '5/25/2023':{'start': 'bruin', 'end': 'draws', 'sequence': 'bruin, brain, drain, drawn, draws'},
    '5/26/2023':{'start': 'fresh', 'end': 'flack', 'sequence': 'fresh, flesh, flash, flask, flack'},
    '5/27/2023':{'start': 'shore', 'end': 'snoot', 'sequence': 'shore, short, shout, snout, snoot'},
    '5/28/2023':{'start': 'blood', 'end': 'broom', 'sequence': 'blood, bloom, gloom, groom, broom'},
    '5/29/2023':{'start': 'cordy', 'end': 'works', 'sequence': 'cordy, wordy, wormy, worms, works'},
    '5/30/2023':{'start': 'graze', 'end': 'trove', 'sequence': 'graze, grave, grove, prove, trove'},
    '5/31/2023':{'start': 'worth', 'end': 'force', 'sequence': 'worth, forth, forty, forte, force'},
    '6/1/2023':{'start': 'emote', 'end': 'store', 'sequence': 'emote, smote, smoke, stoke, store'},
    '6/2/2023':{'start': 'screw', 'end': 'throe', 'sequence': 'screw, shrew, threw, throw, throe'},
    '6/3/2023':{'start': 'deems', 'end': 'stets', 'sequence': 'deems, seems, stems, stews, stets'},
    '6/4/2023':{'start': 'germs', 'end': 'grams', 'sequence': 'germs, terms, teams, trams, grams'},
    '6/5/2023':{'start': 'taken', 'end': 'liked', 'sequence': 'taken, taker, laker, liker, liked'},
    '6/6/2023':{'start': 'watch', 'end': 'ditch', 'sequence': 'watch, patch, pitch, hitch, ditch'},
    '6/7/2023':{'start': 'board', 'end': 'beaus', 'sequence': 'board, beard, bears, beans, beaus'},
    '6/8/2023':{'start': 'moods', 'end': 'hoops', 'sequence': 'moods, woods, foods, hoods, hoops'},
    '6/9/2023':{'start': 'flank', 'end': 'trunk', 'sequence': 'flank, frank, drank, drunk, trunk'},
    '6/10/2023':{'start': 'chink', 'end': 'joins', 'sequence': 'chink, chins, coins, loins, joins'},
    '6/11/2023':{'start': 'flood', 'end': 'crook', 'sequence': 'flood, blood, brood, brook, crook'},
    '6/12/2023':{'start': 'wakes', 'end': 'cafes', 'sequence': 'wakes, makes, lakes, cakes, cafes'},
    '6/13/2023':{'start': 'worth', 'end': 'girth', 'sequence': 'worth, forth, firth, birth, girth'},
    '6/14/2023':{'start': 'quint', 'end': 'quite', 'sequence': 'quint, quirt, quirk, quire, quite'},
    '6/15/2023':{'start': 'phone', 'end': 'prose', 'sequence': 'phone, prone, probe, prove, prose'},
    '6/16/2023':{'start': 'stale', 'end': 'snarl', 'sequence': 'stale, scale, scare, snare, snarl'},
    '6/17/2023':{'start': 'virus', 'end': 'sides', 'sequence': 'virus, vires, wires, sires, sides'},
    '6/18/2023':{'start': 'blend', 'end': 'grand', 'sequence': 'blend, blind, bland, gland, grand'},
    '6/19/2023':{'start': 'known', 'end': 'knots', 'sequence': 'known, knows, knops, knobs, knots'},
    '6/20/2023':{'start': 'brush', 'end': 'crept', 'sequence': 'brush, crush, crust, crest, crept'},
    '6/21/2023':{'start': 'carer', 'end': 'waver', 'sequence': 'carer, cater, later, water, waver'},
    '6/22/2023':{'start': 'heads', 'end': 'gears', 'sequence': 'heads, heaps, hears, years, gears'},
    '6/23/2023':{'start': 'while', 'end': 'shine', 'sequence': 'while, whine, whiny, shiny, shine'},
    '6/24/2023':{'start': 'rimes', 'end': 'dives', 'sequence': 'rimes, mimes, times, dimes, dives'},
    '6/25/2023':{'start': 'phage', 'end': 'least', 'sequence': 'phage, phase, pease, lease, least'},
    '6/26/2023':{'start': 'outen', 'end': 'waken', 'sequence': 'outen, oaten, oaken, taken, waken'},
    '6/27/2023':{'start': 'point', 'end': 'bring', 'sequence': 'point, print, prink, brink, bring'}
}


def index(request):
    # return HttpResponse('Hello, world!')
    # (homes, roger)
    todays_date = date.today()
    date_str = '{}/{}/{}'.format(todays_date.month, todays_date.day, todays_date.year)
    # pair = random.choice(LADDER_PAIRS) 
    pair = {}
    should_random = request.GET.get('random')
    if not should_random:
        pair = DATE_LADDER_PAIRS[date_str]
    else:
        rndm = random.choice(list(DATE_LADDER_PAIRS))
        pair = DATE_LADDER_PAIRS[rndm]

    solution_words = pair['sequence'].split(', ')

    context = {
        'start_word': pair['start'],
        'end_word': pair['end'],
        'answer_str': pair['sequence'],
        'solution': solution_words
    }
    return render(request, 'home/index.html', context)
